max_episode: 16
max_cycle: 50
max_epoch: 200

max_frames: 5000000
save_freq: 1
video_freq: 10
window_size: 100

gradient_step: 40
reset_freq: 1000000000

agent:
  hidden_dim: 64
  layer_count: 3

  actor_lr: 0.0003
  actor_lr_min: 0.0001
  ac_scheduler_steps: 50000

  critic_lr: 0.0003
  critic_lr_min: 0.0001
  cr_scheduler_steps: 50000

  alpha_lr: 0.0003

  # TQC specific parameters
  num_critics: 5
  top_quantiles_to_drop: 2

  buffer_type: "HER"
  max_len: 1000000
  alpha: 0.6

  batch_size: 1024
  gamma: 0.95
  ac_update_freq: 1

  noise_std: 0.0
  noise_clamp: 0.0

  policy_noise: 0.0
  grad_clip: 5.0
  tau: 0.05

  beta: 0.4
  beta_end: 10000

  k_future: 4
  max_eps_len: 50
