max_episode: 16
max_cycle: 50 
max_epoch: 300  # Increased for most complex task

max_frames: 12000000  # Increased for most complex task
save_freq: 1
video_freq: 10
window_size: 100

gradient_step: 40
reset_freq: 1000000000

agent:
  hidden_dim: 320  # Modest increase from 256 - compromise between capacity and stability
  layer_count: 3

  actor_lr: 0.0003  # Keep same as reach
  actor_lr_min: 0.0001
  ac_scheduler_steps: 60000  # Slightly longer schedule

  critic_lr: 0.0003  # Keep same as reach
  critic_lr_min: 0.0001
  cr_scheduler_steps: 60000  # Slightly longer schedule

  alpha_lr: 0.0003

  buffer_type: "HER"
  max_len: 1000000
  alpha: 0.6

  batch_size: 512  # Keep same as reach - stability is key
  gamma: 0.98
  ac_update_freq: 1

  noise_std: 0.0
  noise_clamp: 0.0

  policy_noise: 0.0
  grad_clip: 2.0
  tau: 0.005

  beta: 0.4
  beta_end: 10000

  k_future: 4
  max_eps_len: 50 