max_episode: 32
max_cycle: 50 
max_epoch: 200

max_frames: 5000000
save_freq: 1
video_freq: 1000000
window_size: 100

gradient_step: 40
reset_freq: 25

agent:
  hidden_dim: 256
  layer_count: 3

  actor_lr: 0.001
  actor_lr_min: 0.0001
  # Based on the global gradient counter
  ac_scheduler_steps: 400000

  critic_lr: 0.001
  critic_lr_min: 0.0001
  # Based on the global gradient counter
  cr_scheduler_steps: 400000

  buffer_type: "HER"
  max_len: 1000000
  alpha: 0.6

  batch_size: 256
  gamma: 0.98
  # Based on the global gradient counter
  ac_update_freq: 2

  noise_std: 0.1
  noise_clamp: 0.5

  policy_noise: 0.2
  smooth_coeff: 0.003
  grad_clip: 2.0
  tau: 0.005

  beta: 0.4
  beta_end: 10000

  k_future: 4
  max_eps_len: 50