max_frames: 5000000
save_freq: 10000
video_freq: 100000
window_size: 100

gradient_step: 40
reset_freq: 200000

agent:
  hidden_dim: 64
  layer_count: 3

  actor_lr: 0.00025
  actor_lr_min: 0.00025
  ac_scheduler_steps: 10000

  critic_lr: 0.001
  critic_lr_min: 0.001
  cr_scheduler_steps: 10000

  buffer_type: "HER"
  max_len: 1000000
  alpha: 0.6

  batch_size: 128
  gamma: 0.98
  ac_update_freq: 4

  noise_std: 0.1
  noise_std_min: 0.01
  noise_std_end: 10000

  noise_clamp: 0.5
  noise_clamp_min: 0.1
  noise_clamp_end: 10000

  policy_noise: 0.2
  smooth_coeff: 0.003
  grad_clip: 2.0

  beta: 0.4
  beta_end: 10000

  k_future: 4
  max_eps_len: 50
